apiVersion: apps/v1
kind: Deployment
metadata:
  name: resturant-website
  labels:
    app: resturant-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resturant-website
  template:
    metadata:
      labels:
        app: resturant-website
    spec:
      containers:
      - name: website
        image: prvinsm21/resturant-website:replaceImageTag
        ports:
        - containerPort: 8080
