apiVersion: apps/v1
kind: Deployment
metadata:
  name: resturant-website
  labels:
    app: resturant-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resturant-website
  template:
    metadata:
      labels:
        app: resturant-website
    spec:
      containers:
      - name: resturant-website
        image: prvinsm21/resturant-website:replaceImageTag
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
